[package]
name = "quickget-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
dirs = "5.0.1"
quickget_ci = { path = "../quickget_ci" }
reqwest = { version = "0.12.4", features = ["blocking"] }
serde_json = "1.0.117"
toml = "0.8.13"
