[workspace.package]
license = "GPL-3.0"

[workspace]
members = [
    "quickemu",
    "quickget/cli",
    "quickget/core",
    "quickemu/core",
    "quickemu/cli",
]

resolver = "2"

[profile.release]
strip = true
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"
