[package]
name = "quickget_ci"
version = "0.1.0"
edition = "2021"

[dependencies]
quickemu-rs = { path = "../quickemu" }
regex = "1.10.4"
reqwest = { version = "0.12.4", features = ["blocking"] }
serde = "1.0.202"
serde_json = "1.0.117"
